 name: Complex Workflow
 
 on: push
 
 jobs:
  job1:
    name: Print Date Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print date
        run: | 
          date
  job2:
    name: Print Date Windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print date
        run: | 
          date
  job3:
    name: Print Date Mac
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print date
        run: | 
          date
          
  job4:
    name: Print Date Linux 2
    runs-on: ubuntu-18.04    
    needs: [job1, job2, job3]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print date
        run: | 
          date          
