 name: Complex Workflow
 
 on: push
 
 jobs:
  job1:
    name: Print Date Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: print date
        run: | 
          date
